### ISSUE TITLE
Incompatibility with Oh The Biomes You'll Go

### ISSUE THREAD

**Issue by PakoJones88** [Asek3/Radium#51]
Minecraft version: **1.18.2**
Forge version: **1.18.2-forge-40.1.0**
Radium version: **radium-0.7.10**
BYG version: **Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4.2**

No crash report was generated. The console says the following:

```java
21:27:20.708
Preparing to launch minecraft client for 1.18.2-forge-40.1.0
21:27:22.627
Minecraft client 1.18.2-forge-40.1.0 is ready to start.
21:27:22.627
Starting!
21:27:23.009
Version does not support log configuration, will assume one plaintext entry per line
21:27:24.248
2022-07-30 21:27:24,237 main WARN Advanced terminal features are not available in this environment
21:27:24.397
[21:27:24] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, MilitarZ2112, --version, 1.18.2-forge-40.1.0, --gameDir, C:\Users\mmaan\AppData\Roaming\.minecraft, --assetsDir, C:\Users\mmaan\AppData\Roaming\.minecraft\assets, --assetIndex, 1.18, --uuid, 4805fbac304e4ae3baa29d07d538f42b, --accessToken, ????????, --clientId, NzJhZjVkZGItMmNiMC00Yjg0LTkxNzEtMWJiYTI0Nzc3OTlm, --xuid, 2535462651969428, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 40.1.0, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914]
21:27:24.400
[21:27:24] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.1 by Microsoft
21:27:24.489
[21:27:24] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/mmaan/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2314!/ Service=ModLauncher Env=CLIENT
21:27:24.785
[21:27:24] [main/ERROR] [ne.mi.fm.lo.ModSorter/LOADING]: Missing mandatory dependencies: terrablender
21:27:25.542
[21:27:25] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
21:27:25.546
[21:27:25] [main/ERROR] [mixin/]: Mixin config radium.mixins.json does not specify "minVersion" property
21:27:25.557
[21:27:25] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.18.2-forge-40.1.0, --gameDir, C:\Users\mmaan\AppData\Roaming\.minecraft, --assetsDir, C:\Users\mmaan\AppData\Roaming\.minecraft\assets, --uuid, 4805fbac304e4ae3baa29d07d538f42b, --username, MilitarZ2112, --assetIndex, 1.18, --accessToken, ????????, --clientId, NzJhZjVkZGItMmNiMC00Yjg0LTkxNzEtMWJiYTI0Nzc3OTlm, --xuid, 2535462651969428, --userType, msa, --versionType, release]
21:27:25.654
[21:27:25] [main/INFO] [Radium/]: Loaded configuration file for Radium: 100 options available, 0 override(s) found
21:27:27.627
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
21:27:27.627
at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
21:27:27.627
at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
21:27:27.627
at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
21:27:27.627
at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
21:27:27.627
at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
21:27:27.627
at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
21:27:27.627
at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
21:27:27.627
at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
21:27:27.627
Caused by: java.lang.reflect.InvocationTargetException
21:27:27.627
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
21:27:27.627
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
21:27:27.627
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
21:27:27.627
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
21:27:27.627
at MC-BOOTSTRAP/fmlloader@1.18.2-40.1.0/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31)
21:27:27.627
at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
21:27:27.627
... 7 more
21:27:27.627
Caused by: java.lang.RuntimeException: java.lang.IllegalAccessError: class me.jellysquid.mods.lithium.common.shapes.VoxelShapeSimpleCube tried to access method 'void net.minecraft.world.phys.shapes.VoxelShape.<init>(net.minecraft.world.phys.shapes.DiscreteVoxelShape)' (me.jellysquid.mods.lithium.common.shapes.VoxelShapeSimpleCube is in module radium@0.7.10 of loader 'TRANSFORMER' @625dfff3; net.minecraft.world.phys.shapes.VoxelShape is in module minecraft@1.18.2 of loader 'TRANSFORMER' @625dfff3)
at MC-BOOTSTRAP/fmlloader@1.18.2-40.1.0/net.minecraftforge.fml.loading.BackgroundWaiter.runAndTick(BackgroundWaiter.java:29)
21:27:27.627
at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.main.Main.main(Main.java:138)
21:27:27.627
... 13 more
21:27:27.627
Caused by: java.lang.IllegalAccessError: class me.jellysquid.mods.lithium.common.shapes.VoxelShapeSimpleCube tried to access method 'void net.minecraft.world.phys.shapes.VoxelShape.<init>(net.minecraft.world.phys.shapes.DiscreteVoxelShape)' (me.jellysquid.mods.lithium.common.shapes.VoxelShapeSimpleCube is in module radium@0.7.10 of loader 'TRANSFORMER' @625dfff3; net.minecraft.world.phys.shapes.VoxelShape is in module minecraft@1.18.2 of loader 'TRANSFORMER' @625dfff3)
21:27:27.627
at TRANSFORMER/radium@0.7.10/me.jellysquid.mods.lithium.common.shapes.VoxelShapeSimpleCube.<init>(VoxelShapeSimpleCube.java:31)
21:27:27.627
at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.phys.shapes.Shapes.m_166049_(Shapes.java:1601)
21:27:27.627
at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.phys.shapes.Shapes.m_83048_(Shapes.java:50)
21:27:27.627
at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.phys.shapes.Shapes.<clinit>(Shapes.java:26)
21:27:27.627
at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.block.Block.m_49796_(Block.java:138)
21:27:27.627
at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.block.SaplingBlock.<clinit>(SaplingBlock.java:20)
21:27:27.627
at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.carver.CarverDebugSettings.<clinit>(CarverDebugSettings.java:9)
21:27:27.627
at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.carver.CarverConfiguration.m_190634_(CarverConfiguration.java:16)
21:27:27.627
at MC-BOOTSTRAP/datafixerupper@4.1.27/com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76)
21:27:27.627
at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.carver.CarverConfiguration.<clinit>(CarverConfiguration.java:12)
21:27:27.627
at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.carver.WorldCarver.<clinit>(WorldCarver.java:30)
21:27:27.627
at TRANSFORMER/minecraft@1.18.2/net.minecraft.data.worldgen.Carvers.<clinit>(Carvers.java:19)
21:27:27.627
at TRANSFORMER/minecraft@1.18.2/net.minecraft.data.BuiltinRegistries.m_206400_(BuiltinRegistries.java:45)
21:27:27.627
at TRANSFORMER/minecraft@1.18.2/net.minecraft.data.BuiltinRegistries.m_206392_(BuiltinRegistries.java:101)
21:27:27.627
at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
21:27:27.627
at TRANSFORMER/minecraft@1.18.2/net.minecraft.data.BuiltinRegistries.<clinit>(BuiltinRegistries.java:100)
21:27:27.627
at TRANSFORMER/minecraft@1.18.2/net.minecraft.core.Registry.<clinit>(Registry.java:633)
21:27:27.627
at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:44)
21:27:27.627
at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.main.Main.lambda$main$0(Main.java:138)
21:27:27.627
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
21:27:27.627
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
21:27:27.627
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
21:27:27.627
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
21:27:27.627
at java.base/java.lang.Thread.run(Thread.java:833)
21:27:28.162
Process crashed with exit code 1

**Comment by PakoJones88** [comment]
I'm sorry. I had multiple incompatibility issues in my modpack and when isolating the mods I completely forgot TerraBlender. Tested it again with TerraBlender and now it works.

**Comment by DeleteMetaInf** [comment]
Do you mean without TerraBlender? Is Radium Reforged incompatible with TerraBlender?
