### ISSUE TITLE
Error on update

### ISSUE THREAD

**Issue by Atlantispy** [Asek3/Radium#9]
29.01 14:53:02 [Server] Server thread/ERROR Encountered an unexpected exception
29.01 14:53:02 [Server] INFO java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonArray.iterator()" because "$$1" is null
29.01 14:53:02 [Server] INFO at net.minecraft.server.players.StoredUserList.m_11399_(StoredUserList.java:121) ~[server-1.18.1-20211210.034407-srg.jar%2394!/:?]
29.01 14:53:02 [Server] INFO at net.minecraft.server.dedicated.DedicatedPlayerList.m_139596_(DedicatedPlayerList.java:84) ~[server-1.18.1-20211210.034407-srg.jar%2394!/:?]
29.01 14:53:02 [Server] INFO at net.minecraft.server.dedicated.DedicatedPlayerList.<init>(DedicatedPlayerList.java:23) ~[server-1.18.1-20211210.034407-srg.jar%2394!/:?]
29.01 14:53:02 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:169) ~[server-1.18.1-20211210.034407-srg.jar%2394!/:?]
29.01 14:53:02 [Server] INFO at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:644) ~[server-1.18.1-20211210.034407-srg.jar%2394!/:?]
29.01 14:53:02 [Server] INFO at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%2394!/:?]
29.01 14:53:02 [Server] INFO at java.lang.Thread.run(Thread.java:833) [?:?]
29.01 14:53:02 [Server] Server thread/ERROR Exception caught during firing event: Cannot invoke "net.minecraft.server.MinecraftServer.m_129843_(net.minecraft.world.level.storage.LevelResource)" because the return value of "net.minecraftforge.server.ServerLifecycleHooks.getCurrentServer()" is null
29.01 14:53:02 [Server] INFO Index: 6
29.01 14:53:02 [Server] INFO Listeners:
29.01 14:53:02 [Server] INFO 0: HIGH
29.01 14:53:02 [Server] INFO 1: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/server/ServerStoppedEvent;)V
29.01 14:53:02 [Server] INFO 2: NORMAL
29.01 14:53:02 [Server] INFO 3: ASM: class shadows.placebo.util.PlaceboTaskQueue stopped(Lnet/minecraftforge/event/server/ServerStoppedEvent;)V
29.01 14:53:02 [Server] INFO 4: net.minecraftforge.eventbus.EventBus$$Lambda$3754/0x00000008015e1360@3ef15807
29.01 14:53:02 [Server] INFO 5: net.minecraftforge.eventbus.EventBus$$Lambda$3754/0x00000008015e1360@4e3b7699
29.01 14:53:02 [Server] INFO 6: ASM: class de.geheimagentnr1.world_pre_generator.handlers.ForgeEventHandler handleServerStoppedEvent(Lnet/minecraftforge/event/server/ServerStoppedEvent;)V
29.01 14:53:02 [Server] INFO java.lang.NullPointerException: Cannot invoke "net.minecraft.server.MinecraftServer.m_129843_(net.minecraft.world.level.storage.LevelResource)" because the return value of "net.minecraftforge.server.ServerLifecycleHooks.getCurrentServer()" is null
29.01 14:53:02 [Server] INFO at TRANSFORMER/world_pre_generator@2.0.1/de.geheimagentnr1.world_pre_generator.save.PregenerationWorldPersistencer.getFilePath(PregenerationWorldPersistencer.java:43)
29.01 14:53:02 [Server] INFO at TRANSFORMER/world_pre_generator@2.0.1/de.geheimagentnr1.world_pre_generator.save.PregenerationWorldPersistencer.save(PregenerationWorldPersistencer.java:67)
29.01 14:53:02 [Server] INFO at TRANSFORMER/world_pre_generator@2.0.1/de.geheimagentnr1.world_pre_generator.handlers.ForgeEventHandler.handleServerStoppedEvent(ForgeEventHandler.java:36)
29.01 14:53:02 [Server] INFO at net.minecraftforge.eventbus.ASMEventHandler_90_ForgeEventHandler_handleServerStoppedEvent_ServerStoppedEvent.invoke(.dynamic)
29.01 14:53:02 [Server] INFO at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
29.01 14:53:02 [Server] INFO at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
29.01 14:53:03 [Server] INFO at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
29.01 14:53:03 [Server] INFO at TRANSFORMER/forge@39.0.58/net.minecraftforge.server.ServerLifecycleHooks.handleServerStopped(ServerLifecycleHooks.java:125)
29.01 14:53:03 [Server] INFO at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:714)
29.01 14:53:03 [Server] INFO at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258)
29.01 14:53:03 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:833)

Tried updating from 0.7.7c to 0.7.7e and receiving this error in console. Currently working to download the world, and reinstall the server fresh.

**Comment by Atlantispy** [comment]
Having fully reinstalled server it seems to be resolved
